resources:
  - name: test_ci_gitrepo
    type: gitRepo
    integration: github
    pointer:
      sourceName: skylark03/test_ci_repo
      branch: master
      buildOnPullRequest: true
  - name: myaws
    type: integration
    integration: myaws

jobs:
  - name: my_ci_job
    type: runSh
    steps:
      - IN: test_ci_gitrepo
      - TASK:
        - script: echo "Hello, World!"
